import type { Metadata } from 'next';

import { ReportsView, type ReportsResult } from '@/components/reports/reports-view';
import { PageHeader } from '@/components/ui/page-primitives';
import { getGrantedPermissions } from '@/lib/authz/guard';
import { getSalesSummary } from '@/lib/dashboard/service';

export const metadata: Metadata = {
  title: 'Reports — A.V. Jewelry Operations',
};

export const dynamic = 'force-dynamic';

/**
 * Reports (Bible §25). Roadmap Phase 9.
 *
 * The ONE approved report — the sales summary — on its own screen. Nothing is
 * invented to fill the page. Reading it is export-gated (export_data_reports);
 * the report is generated by report_sales_summary() under the caller's RLS scope
 * and audited in the domain layer.
 */
export default async function ReportsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const from = typeof params.from === 'string' ? params.from : '';
  const to = typeof params.to === 'string' ? params.to : '';

  const permissions = await getGrantedPermissions();
  const canExport = permissions.has('export_data_reports');

  // Viewing is broad: any active staff may run the on-screen summary. Only
  // export/download is gated by export_data_reports (canExport, passed through).
  let result: ReportsResult | null = null;
  if (from && to) {
    result = await getSalesSummary(
      new Date(from).toISOString(),
      new Date(to).toISOString(),
    );
  }

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Sales summary — verified money only. A report grants no authority over the records in it."
      />
      <ReportsView canExport={canExport} from={from} to={to} result={result} />
    </div>
  );
}
