import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { ReportsView, type ReportsResult } from '@/components/reports/reports-view';
import { ExportAllButton } from '@/components/export/export-all-button';
import { PageHeader } from '@/components/ui/page-primitives';
import {
  canOpenPage,
  getGrantedPermissions,
  requireActiveStaff,
} from '@/lib/authz/guard';
import { getSalesSummary } from '@/lib/dashboard/service';

export const metadata: Metadata = {};

export const dynamic = 'force-dynamic';

/**
 * Reports (Bible §25). Roadmap Phase 9.
 *
 * The ONE approved report — the sales summary — on its own screen. Nothing is
 * invented to fill the page. Reading it is export-gated (export_data_reports);
 * the report is generated by report_sales_summary() under the caller's RLS scope
 * and audited in the domain layer.
 */
export default async function ReportsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  // Page access (Portal & Access). A member without this permission cannot open
  // the page — by link OR by typing the URL. A Super Admin holds it implicitly.
  if (!(await canOpenPage('view_reports'))) notFound();
  const params = await searchParams;
  const from = typeof params.from === 'string' ? params.from : '';
  const to = typeof params.to === 'string' ? params.to : '';

  const [permissions, staff] = await Promise.all([
    getGrantedPermissions(),
    requireActiveStaff(),
  ]);
  const canExport = permissions.has('export_data_reports');
  // Full-data export is Owner / Selected Admin only.
  const canExportAll = staff.roleKey === 'owner' || staff.roleKey === 'selected_admin';

  // Viewing is broad: any active staff may run the on-screen summary. Only
  // export/download is gated by export_data_reports (canExport, passed through).
  // The picker gives Manila calendar days. `new Date('YYYY-MM-DD')` is UTC midnight = 08:00
  // Manila, which made a one-day report an empty instant and clipped every range by 8 hours
  // on both ends (system audit 2026-09-16). Bound the range to full Manila days instead, and
  // refuse malformed params rather than throwing a RangeError into the error boundary.
  const isDay = (v: string) => /^\d{4}-\d{2}-\d{2}$/.test(v);
  let result: ReportsResult | null = null;
  if (from && to && isDay(from) && isDay(to)) {
    result = await getSalesSummary(
      `${from}T00:00:00.000+08:00`,
      `${to}T23:59:59.999+08:00`,
    );
  }

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Sales summary — verified money only. A report grants no authority over the records in it."
      />
      {canExportAll ? (
        <div className="mb-4 flex justify-end">
          <ExportAllButton isOwner={staff.roleKey === 'owner'} />
        </div>
      ) : null}
      <ReportsView canExport={canExport} from={from} to={to} result={result} />
    </div>
  );
}
